### ISSUE TITLE
FunctionDeclSyntax does not expand body

### ISSUE THREAD

**Issue by zzyptr** [swiftlang/swift-syntax#2880] opened 2024-10-11 02:09 UTC
### Description

FunctionDeclSyntax does not expand body as expected. 

```swift
let functionDeclaration = FunctionDeclSyntax(
    name: .identifier("foo"),
    signature: FunctionSignatureSyntax(parameterClause: FunctionParameterClauseSyntax(parameters: [])),
    body: CodeBlockSyntax(statements: [])
)
```
will expand to 
```swift
func foo() 
```
no body

**Comment by ahoppen** [comment] 2024-10-11 02:13
Synced to Apple’s issue tracker as rdar://137723591

**Comment by ahoppen** [comment] 2024-10-14 16:30
I was unable to reproduce the issue. 

```swift
let functionDeclaration = FunctionDeclSyntax(
  name: .identifier("foo"),
  signature: FunctionSignatureSyntax(parameterClause: FunctionParameterClauseSyntax(parameters: [])),
  body: CodeBlockSyntax(statements: [])
)
print(functionDeclaration.formatted())
```
 
prints

```swift
func foo() {
}
```

Which contains a body. 

Are you doing anything differently? If so, can you share a reproducing project?

**Comment by zzyptr** [comment] 2024-10-15 10:18
I am sorry. I found the body of the function was removed by a body macro that with a implementation of ```return []```

**Comment by sidepelican** [comment] 2024-11-26 05:45
@zzyptr Could you close this issue?

**Closed** 2024-11-26 05:46 UTC
Labels: bug
